version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: zomato_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./data/localstack:/var/lib/localstack"

  streamlit_app:
    build: .
    container_name: zomato_streamlit_app
    ports:
      - "8501:8501"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ".:/app"
    depends_on:
      - localstack
